version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./FrontEnd_NGINX/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BackEnd/mysql-config:/etc/mysql/conf.d
    
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local



networks:
  app-network:
    driver: bridge